# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

spring:
  profiles:
    active: [ "database", "springdoc", "oauth2", "s3", "map"]
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: 'Asia/Seoul'


# 오류 처리
server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: false  # 로컬 개발 환경(HTTP)에서 테스트할 때만 사용, 배포할 때는 true
  error:
    include-exception: true
    include-stacktrace: always
  #port 설정
  port: 8080